[phases.setup]
commands = ["dotnet --version", "go version"]

[dependencies]
runtime = ["dotnet-sdk", "go_1_21"]

[phases.build]
commands = [
  "cd SeleniumTests && dotnet restore && dotnet build",
  "cd board-games-api && go mod tidy && go build -o app ."
]

[phases.start]
command = "cd board-games-api && ./app"
