[phases.setup]
commands = [
    "dotnet --version",
    "go version"
]

[phases.build]
commands = [
    "cd board-games-api && go build -o app .",
    "cd SeleniumTests && dotnet restore && dotnet build"
]

[phases.start]
command = "cd board-games-api && ./app"
